language: cpp

compiler:
  - gcc

before_install:
  - wget http://google-styleguide.googlecode.com/svn/trunk/cpplint/cpplint.py
  - chmod +x cpplint.py
  - sudo mv cpplint.py /usr/local/bin

script:
  - ./waf configure --enable-gcov
  - ./waf --checkall
  - ./waf cpplint

after_success:
  - coveralls -b build -r . -E ".*_test.cpp" -E ".*/.unittest-gtest/.*" -x .cpp -x .hpp
