language: cpp

compiler:
  - gcc

before_install:
  - wget http://google-styleguide.googlecode.com/svn/trunk/cpplint/cpplint.py
  - chmod +x cpplint.py
  - sudo mv cpplint.py /usr/local/bin

script:
  - ./waf configure
  - ./waf --checkall
  - ./waf cpplint
